# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    
    # Applications    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        allowPrerelease: true
      settings:
        id: "Microsoft.VisualStudioCode"
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: wsl
      directives:
        allowPrerelease: true
      settings:
        id: "9P9TQF7MRM4R"
        source: msstore
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ubuntu
      directives:
        description:  ubuntu
        allowPrerelease: true
      settings:
        id: "9PDXGNCFSCZV"
        source: msstore
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: docker-desktop
      directives:
        allowPrerelease: true
      settings:
        id: "Docker.DockerDesktop"
        source: winget

  configurationVersion: 0.2.0
  