name: Long Running Release Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Run every five minutes

jobs:

  exit-fork-check:
    uses: ./.github/workflows/exit-fork-scheduled-workflow.yml
  
  test:
    needs: exit-fork-check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/exit-when-scheduled-on-fork
      - uses: ./.github/actions/checkout-repo
      - uses: ./.github/actions/setup-go
