name: Reusable Echo Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo reusable workflow message
        run: echo "reusable workflow invoked"